
=head1 NAME

OpenTracing::Role - API definition for OpenTransport implementations

=head1 DESCRIPTION

=head2 Required Reading

In order to understand the Perl platform API, one must first be familiar with
L<the OpenTracing project|http://opentracing.io/>
and
L<terminology|http://opentracing.io/documentation/pages/spec>
more generally.

=head1 SYNOPSIS

=head2 Singleton Initialization

    use Package::Alias 'OpenTracing' => 'Perceptyx::OpenTracing';
    
    OpenTracing->set_global_tracer( Some::Tracer::Implementation->new( ... ) );
    
=cut

=head1 ABOUT

The interfaces being defined as roles
( using <Role::Tiny|https://metacpan.org/pod/Role::Tiny )
and use `around` method modifiers, instead of `require`, we do want to wrap the
method in type checking
( using <Type::Tiny|https://metacpan.org/pod/Type::Tiny> and friends ).
